### ISSUE TITLE
Incorrect number of shown feeds on the main page

### ISSUE THREAD

**Issue by lapineige** [FreshRSS/FreshRSS#1582]
Hello, 

I'm using FreshRSS 1.7, and since a few hours, my main feed page (I mean, the default one) is showing only a few articles. Now it's just 6, before it was 3, some reloads before it was a bit more.
I have the normal account (20) on every other page, and even if I change the number of shown feeds the result is the same.

Reloading the web server (nginx) change nothing.

**Comment by lapineige** [comment]
It sounds like the number of show feeds increases when new feeds are added.

It looks like older feeds can't be shown.

**Comment by Alkarex** [comment]
Try to run a database optimization and/or purge in FreshRSS settings.

**Comment by lapineige** [comment]
I don't know if it will work. I always get a time out (125 MB database, it takes time ^^).
In that case, should I wait ? I suppose it still does it in the background.

**Comment by Alkarex** [comment]
My database is 430MB at it works fine. Maybe you could try to increase a bit your timeout values in your php.ini ?

**Comment by lapineige** [comment]
Actually, the "timed-out" try increased the database size to 160MB ^^ (and changed nothing to my config)

Do you know which file I should edit ? I have several php.ini files:

> /etc/php.ini
> /etc/php5/cli/php.ini
> /etc/php5/fpm/php.ini

(and also, do you know the name of the parameter to change ? )

Thanks :)

**Comment by Alkarex** [comment]
Maybe the timeout is due to a configuration in your Web server and not in PHP. In PHP, one of the relevant line is:
`max_execution_time = 60`
Except the CLI one, you can update the two other php.ini files (I do not know which one is used. You can know that by running a `phpinfo()` from your Web browser such as:

```php
<?php
phpinfo();
```

**Comment by lapineige** [comment]
In fact /etc/php.ini is empty.
I tried with the fpm one, with 120 seconds, not working. I'll try again.

For the web browser instructions, I used it in the (Firefox) console, syntax error :/

**Comment by Alkarex** [comment]
It must be in a PHP file on your server, e.g. `phpinfo.php` and must be called from your browser, e.g. `http://your.example.net/phpinfo.php`

**Comment by lapineige** [comment]
Ok thanks, it's the fpm file.
I reloaded the service after setting the value to 30min.

Still a time-out after a few tens of seconds (default value is 30 sec).
Sounds like nothing changed.

I also checked the processes, no php-fpm stuff related to freshrss (and by the way, no process with freshrss in the name)

**Comment by lapineige** [comment]
Still not able to do the database optimisation but... issue solved, without any new intervention.
I don't know what happened

**Comment by lapineige** [comment]
The issue is here again, still at the exact same "time" in the feed list.

Do you have an idea for the database optimization ? Is it possible to do it from the command line ?

**Comment by Alkarex** [comment]
What database are you using?
Could you please check the content of the `entrytmp` table?
I will make a CLI version of this database maintenance stuff. Could you please open a new dedicated issue?

**Comment by lapineige** [comment]
It's MariaDB

> Could you please check the content of the entrytmp table?

Could you give me an hint for the command to use ? (I'm kind of bad with SQL stuff ^^)

**Comment by Alkarex** [comment]
Sorry for the delay; I forgot this issue. A few examples:

```sh
mysql -u freshrss -p freshrss
```

```sql
show tables;

select * from freshrss_lapineige_entrytmp;
```

(Should be empty)

**Comment by lapineige** [comment]
Thanks for the commands.
It's empty indeed (and the table is `lapineige_entrytmp`).

**Comment by Alkarex** [comment]
Good, it is supposed to be empty, except when there is an ongoing refresh.
Could you please try to make a screenshot showing the problem?
Please have a look also at your logs (Web browser console, and Web server logs).

**Comment by lapineige** [comment]
Here you can see that the feed list just stops (the issue happened again today): https://framapic.org/ZzDlXe9uWe9q/OcgxXFthM5Pf.png
If I mark any of those feed as read, next time I just don't have them in the list, but no new feed.
It only disappear when I finally mark as read all the feed added after a certain moment (I guess when this "bug" appear).

No error in the console.
(I'll check the logs)

**Comment by lapineige** [comment]
I think I've found more "debug" information about this issue:
First, it seems to appear only when the last feed is from the Youtube feed provided by a RSS Bridge instance (for example: https://bridge.suumitsu.eu/).
And this last feed is the issue : if I mark it as read, problem solved.
And it contains all the following feeds (as a kind of "sub-feed", with just an horizontal shift), and when I mark it read, all the other are marked in the same way (but it only apply to this particular feed).

The author text is also wrong: « Par E html> » instead of « Par [Author]»

**Comment by Alkarex** [comment]
@lapineige Could you please give a try to the latest version of FreshRSS (1.8.0) if this is not already the one you are using? The author HTML issue has been fixed already.

**Comment by lapineige** [comment]
I haven't seen that a new version was released - I'm going to update and test it ASAP :)

**Comment by lapineige** [comment]
Upgrading to 1.8 doesn't solve the issue (even the author HTML).

**Comment by Alkarex** [comment]
@lapineige For the author HTML issue, the fix will only apply to new articles. You can try to purge or delete a problematic feed and add / refresh it again.

**Comment by lapineige** [comment]
Well this should solve the problem, isn't it ?
So I'm closing this issue, I will try to refresh those feeds, we'll see if it happens again :)

**Comment by Alkarex** [comment]
Ok, let us know :-)
