### ISSUE TITLE
Marking Feed last feed of a category as read does not jump to the next feed with unread articles

### ISSUE THREAD

**Issue by ddeimeke** [FreshRSS/FreshRSS#2206]
Hi! I use `<shift><r>` a lot and it works pretty well for unread articles in categories: Once I use the shortcut to mark all articles as read it jumps to the next category with unread articles.

It even works well on feeds with one exception: if I press <shift><r> on the last feed with unread articles in a category, it shows me all categories, even those without unread articles.

In my opionion it should jump to the first feed with unread articles of the next category.

Can you please check?

**Comment by Alkarex** [comment]
Indeed, that is the current behaviour, and that was on purpose to indicate that the whole category has been read. But I see the point of continuing to other feeds without having to use another shortcut.
Currently, the behaviour is not necessarily linear: if there are not more unread feeds after the current one in the current category, it will show unread feeds before the current one in the current category.
I am a bit unsure, so other opinions welcome :-)

**Comment by Frenzie** [comment]
I think I would intuitively expect it to just continue on to the next unread in the relevant following category, possibly looping around at the end. But I seldom use Shift+R.

**Comment by ddeimeke** [comment]
For reasons of consistency, it would be great to either let "r" react the same way as "j" and "k" (use the "alt" key for category-based operations and do nothing if you use <shift><r> on the last feed of a category). Or let <shift><j> AND <shift><r> jump to the next feed with unread articles even if you are on the last feed of a category.

**Comment by Alkarex** [comment]
@ddeimeke I have changed that behaviour in https://github.com/FreshRSS/FreshRSS/pull/2255
Could you please give a try to the /dev branch?

**Comment by ddeimeke** [comment]
Yes, sure.

I don't see a difference in behaviour.

It still works the same. When I do a `<shift><r>` on the last feed of a category, I see a list of read and unread feeds.

**Comment by ddeimeke** [comment]
What I see is, that I jump mit "j" to the next article, after I read the the last unread article it jumps to the first read article of a feed.

**Comment by Alkarex** [comment]
@ddeimeke Ok, the remaining behaviour changes should be addressed by https://github.com/FreshRSS/FreshRSS/pull/2265 if you could git it a try

**Comment by ddeimeke** [comment]
@Alkarex The "j" behaviour is good now. The shift-"r" behaviour still does not work.

**Comment by Alkarex** [comment]
@ddeimeke Are you sure you tried with the changes from today? https://github.com/FreshRSS/FreshRSS/pull/2265 I can merge them in the /dev branch if it is easier to test.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/2265 merged in /dev

**Comment by ddeimeke** [comment]
Hi @Alkarex 

Oh sorry, I thought it was already in DEV.

Tested DEV again. I works perfectly well.

What about using feature branches (or even DEV?), this would make testing much easier.

**Comment by Alkarex** [comment]
No worries, and thanks for the test @ddeimeke 
https://github.com/FreshRSS/FreshRSS/pull/2265 was a branch ;-) (`Alkarex:shortcut-2206`)
I typically try to test a bit a feature / PR (and collect some initial feedback when possible) before merging in /dev for additional testing. I think it is mostly the same than what you are asking :-)

**Comment by ddeimeke** [comment]
Ok, sorry for the inconvinience!
