### ISSUE TITLE
Shortcuts problem when showing articles unfolded

### ISSUE THREAD

**Issue by Pitel** [FreshRSS/FreshRSS#2328]
j/k now (1.14.0) seems to jump by whole page, not article. It was ok in 1.13.

Chrome 75.0.3745.4, Linux

**Comment by Frenzie** [comment]
What do you mean by "whole page" precisely?

**Comment by ggdagg** [comment]
I confirm that I have the same symptom since Freshrss 1.14.0, however it's with Firefox 66.0.1. Before when I used j/k shortcuts it was opening the next/previous article, and the title of the article was at the top of the screen. Now it randomly open the next/previous article in the middle of the article itself, or even jump an article and ends up in the middle of the next one. I have the same issue with the navigation arrows. My options are “normal view”, “show only unread”, “show articles unfolded by default”. For testing, I also tried different themes, but the problem is still here.

Tested on 2 different Firefox 66.0.1 on Linux.

**Comment by Alkarex** [comment]
@Frenzie Were you able to reproduce the issue? I could not (tested on Ubuntu 18.04 LTS with Firefox 66 and Chromium 73)
@Pitel and @ggdagg Could you please try our /dev branch (upcoming 1.14.1), where I have just fixed a number of things regarding shortcuts and mouse clicks?

**Comment by Frenzie** [comment]
No, I wasn't.

**Comment by ggdagg** [comment]
I just tried with 1.14.1-dev, and unfortunately I still have the same issue. Here is a GIF of the test I did, and might help you understand better what I meant: https://imgur.com/a/RPFGPD1
I also tried again with the keyboard shortcuts, and it's also the same. Even worst I would say since the "open next article" key just goes at the bottom of the page and marks all articles as read in my case. This is not shown on the GIF.

It has been test with a brand-new database, same options as before (“normal view”, “show only unread”, “show articles unfolded by default”), and tried on Windows and Linux with Firefox 60.0.2 and 60.6.0esr, respectively.

**Comment by Frenzie** [comment]
Just a shot in the dark here, but on what kind of OS and filesystem are you running the server? Is it possible that something's going wrong with the `filemtime()` so that you're getting the cached version of the older script or something along those lines?

It'll be in the first few lines of the HTML source:
```html
<script src="../scripts/main.js?1554061833" defer="defer" async="async"></script>
```
If you're missing a number, a full refresh (Ctrl+F5) should probably suffice. If there is a number, put the number in https://www.epochconverter.com/ and see if it says something recent. I.e., any result older than about 3 or 4 days ago probably means something's wrong. If so, please share the result and more server details.

For example, my number there converts to `Sunday, March 31, 2019 7:50:33 PM` UTC, when I updated to 1.14 final.

**Comment by Pitel** [comment]
`1554283442` -> 2 days ago.

And my server is Raspberry Pi with latest Raspbian and NginX + PHP 7.3.3.

**Comment by ggdagg** [comment]
Mine is:
`<script src="../scripts/main.js?1554273549" defer="defer" async="async"></script>`

Following your information, 1554273549 is GMT: Wednesday, 3 April 2019 06:39:09.

Details about my server:
- CentOS 7.6.1810
- Filesystem XFS
- Apache/2.4.38
- PHP 7.2.13

**Comment by Alkarex** [comment]
I can reproduce a similar problem with the option *Show articles unfolded by default*

**Comment by Alkarex** [comment]
Should be fixed with https://github.com/FreshRSS/FreshRSS/pull/2336
Tests welcome

**Comment by Alkarex** [comment]
Merged in the /dev branch. Additional tests welcome

**Comment by Pitel** [comment]
Confirming fixed in `dev` branch. :+1: :tada:

**Comment by ggdagg** [comment]
Yes same on my side I confirm that you fixed the problem! Thanks for this quick fix :)

**Comment by Alkarex** [comment]
Thanks for the quick feedback :-)
