### ISSUE TITLE
Can't mark items read/unread if browser left open for a long period of time

### ISSUE THREAD

**Issue by TheFiZi** [FreshRSS/FreshRSS#3475]
I leave FreshRSS open in a tab on my work PC and it seems after enough time passes I can no longer mark items as read/unread.

When I click the envelope icon I get the following error:

`A request has failed, it may have been caused by internet connection problems.`

A F5 and CTRL+F5 does not clear the problem. Blowing away the browsers cache and all session data seems to correct the issue but forces me to login again.

Here is what I got our of my browser console.

![image](https://user-images.githubusercontent.com/1762426/108750560-07688800-74f6-11eb-8a05-9446f77f11bd.png)

**Comment by Frenzie** [comment]
I do that too, sometimes possibly even for weeks on end (with suspend/hibernation in between at night).

There is the default login duration issue fixed in https://github.com/FreshRSS/FreshRSS/pull/3287 but your problem description sounds like it must be something different, unless you're seeing something like "not allowed to access this page"?

**Comment by TheFiZi** [comment]
> 
> 
> I do that too, sometimes possibly even for weeks on end (with suspend/hibernation in between at night).
> 
> There is the default login duration issue fixed in #3287 but your problem description sounds like it must be something different, unless you're seeing something like "not allowed to access this page"?

Looking at that issue I do not think it's the same. This happens in like 1-2 days well before the 30 day cookie limit.

I do wonder how if it happens after I reload my nginx server. I'll have to keep an eye on it next time it happens. I just recently switched from TTRSS so I'm used to leave that open for weeks on end with out session issues.

**Comment by wangxu94** [comment]
I'm having the same issue. Logging out and back in doesn't fix it, which suggests it's not an authentication/cookie issue.

**Comment by Frenzie** [comment]
Does your server have sufficient disk space/memory/etc.? Also please add additional pertinent information, such as which server, PHP version, DB, etc. you use.

**Comment by wangxu94** [comment]
Hey actually you're right. I just had another program go crazy and fill up my temp dir on my server. I've fixed that now so I'll keep observing and report back if I see this issue again. Sorry about the false alarm!

**Comment by Frenzie** [comment]
Great!

Put another way, the OP sounds like a server problem, not a FreshRSS problem. ;-)

**Comment by TheFiZi** [comment]
Disk space:

```bash
[me@localhost~]$ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        1.9G     0  1.9G   0% /dev
tmpfs           1.9G   12K  1.9G   1% /dev/shm
tmpfs           1.9G  162M  1.7G   9% /run
tmpfs           1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/sda4        37G   13G   24G  35% /
/dev/sdb1        40G   29G   12G  71% /var/www
/dev/sdd1        10G  2.2G  7.8G  22% /opt/gitlab
/dev/loop1       50M   50M     0 100% /var/lib/snapd/snap/certbot/952
/dev/loop0       62M   62M     0 100% /var/lib/snapd/snap/core20/904
/dev/loop2       32M   32M     0 100% /var/lib/snapd/snap/snapd/10707
/dev/sda2       976M  247M  663M  28% /boot
/dev/sda1       599M  7.3M  592M   2% /boot/efi
/dev/sde1        11G  1.4G  9.7G  13% /var/opt/gitlab
/dev/sdc1        20G  2.4G   18G  12% /var/lib/mysql
tmpfs           374M     0  374M   0% /run/user/988
tmpfs           374M     0  374M   0% /run/user/1001
tmpfs           374M     0  374M   0% /run/user/1002
/dev/loop3       32M   32M     0 100% /var/lib/snapd/snap/snapd/11036
tmpfs           374M     0  374M   0% /run/user/1000
```

Site files reside in `/var/www` and `/tmp/` resides in `/`

```
PHP 7.4.15 (cli) (built: Feb  2 2021 14:19:57) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.15, Copyright (c), by Zend Technologies

mysql  Ver 15.1 Distrib 10.4.12-MariaDB, for Linux (x86_64) using readline 5.1

nginx version: nginx/1.18.0
```

VM has 2 cores, 4GB of RAM and is running many other web applications just fine.

Will check on disk usage next time the issue comes up.

**Comment by TheFiZi** [comment]
Ah ha, was doing some quick sanity checking and found the problem.

When I do OS updates this command run at the end:

`systemctl reload nginx php-fpm`

I did a `systemctl reload nginx` by itself and FreshRSS continued to work properly.

When I did a `systemctl reload php-fpm` the problem started happening again

That narrows it down, now to figure out why it can't just re-connect to PHP-FPM after a reload.

nginx config:

```nginx
server {
    listen 443 ssl http2;
    server_name rss.fizi.ca;

    #root /var/www/rss.fizi.ca;
    root /var/www/rss.fizi.ca/p;
    index index.html index.htm index.php;

    location / {
            try_files $uri $uri/ /index.html;
    }

        # php files handling
        # this regex is mandatory because of the API
        location ~ ^.+?\.php(/.*)?$ {
                fastcgi_pass unix:/run/php-fpm/www.sock;
                fastcgi_split_path_info ^(.+\.php)(/.*)$;
                # By default, the variable PATH_INFO is not set under PHP-FPM
                # But FreshRSS API greader.php need it. If you have a “Bad Request” error, double check this var!
                # NOTE: the separate $path_info variable is required. For more details, see:
                # https://trac.nginx.org/nginx/ticket/321
                set $path_info $fastcgi_path_info;
                fastcgi_param PATH_INFO $path_info;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
          root /usr/share/nginx/html;
    }

    ssl_certificate /etc/letsencrypt/live/rss.fizi.ca/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/rss.fizi.ca/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/rss.fizi.ca/chain.pem;
    include snippets/ssl.conf;
    include snippets/letsencrypt.conf;
    include snippets/php.conf;
    include snippets/disablelogging.conf;
}
```

**Comment by math-GH** [comment]
Is it still an issue?

**Comment by TheFiZi** [comment]
Looks like the issue was 100% on my end and I just figured it out. Thanks for the prod.

So in my environment I am running CentoS 8 Stream which requires me to use a 3rd party repo to get the latest versions of PHP.

That repo assumes you are using Apache (httpd) and so when PHP updates gets installed it changes all the file permissions on php-fpm related files to be owned by httpd:httpd instead of leaving it alone as nginx:nginx.

I had worked around this issue by writing a script I use to update the OS:

```bash
#!/bin/bash
# Update repo info
dnf updateinfo --refresh

# Update OS
yum update -y
yum autoremove -y

# Run this to fix problems caused by PHP updates assuming you're using apache
chown -R root:nginx /var/lib/php

# Fix owncloud permissions if it gets updated
chown -R nginx:nginx /var/www/owncloud.mydomain.com
# Reload nginx and php-fpm
systemctl reload php-fpm nginx

# Update snaps
snap refresh
```

Turns out the issue was the `chown -R root:nginx /var/lib/php` line. It should be `chown -R nginx:nginx /var/lib/php`

After making that tweak everything is surviving updates and service restarts now.

Sorry for leaving this lying around for so long.
