### ISSUE TITLE
[BUG] SQL error updateFeed: UNIQUE constraint failed: feed.url for feed

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4229]
**To Reproduce**
go to subscription management page
![grafik](https://user-images.githubusercontent.com/1645099/155214804-ee7f3d53-71a3-4513-aa0d-593d1d4f9f02.png)

Copy the feed URL from 1 feed (= feed URL 1)

Open another feed (= feed URL 2)
![grafik](https://user-images.githubusercontent.com/1645099/155214905-82959ff9-22b7-41fb-97cd-4edcb326861c.png)

Paste the feed into the feed URL (=overwrite feed URL 2 with feed URL 1)
![grafik](https://user-images.githubusercontent.com/1645099/155215081-f32c7c55-6aee-4549-9445-35c54a62fc93.png)

save it. Error message "Feed cannot be updated"
![grafik](https://user-images.githubusercontent.com/1645099/155215124-4f0dbf5c-abcc-49e0-8115-31701d3657d4.png)

Go to log and see the error message `SQL error updateFeed: UNIQUE constraint failed: feed.url for feed`
![grafik](https://user-images.githubusercontent.com/1645099/155215180-a03e9aa1-fc3f-477a-b405-e56f0d619476.png)

**Expected behavior**
no error message in log.
Maybe another error text like "Duplicated feed URL"

**Environment information (please complete the following information):**
- FreshRSS version: 1.20.0-dev

**Comment by Alkarex** [comment]
I believe this was solved by https://github.com/FreshRSS/FreshRSS/pull/5038
You are welcome to confirm if you can @math-GH

**Comment by math-GH** [comment]
still reproduce-able

![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/7bbee32c-f5d9-4932-957b-d95901a831d2)

**Comment by Alkarex** [comment]
What database? 
New install or updated from older version?

**Comment by math-GH** [comment]
Database: SQLite
It is my long running dev environment

**Comment by Alkarex** [comment]
Please try with a new user or with a DB exported by `./cli/export-sqlite-for-user.php`
SQLite does not support updates of columns:
https://github.com/FreshRSS/FreshRSS/blob/8280e3d88edb93211fcf2aec15a7b4c1ae4d3813/app/SQL/install.sql.sqlite.php#L111-L112

But I can see that I have not added the autoupdate for PostgreSQL and MySQL:
https://github.com/FreshRSS/FreshRSS/blob/8280e3d88edb93211fcf2aec15a7b4c1ae4d3813/app/SQL/install.sql.pgsql.php#L105-L131

**Comment by Alkarex** [comment]
> SQLite does not support updates of columns:

For reference https://www.sqlite.org/lang_altertable.html#making_other_kinds_of_table_schema_changes

**Comment by Alkarex** [comment]
With https://github.com/FreshRSS/FreshRSS/pull/6387 , there is now an easier method to back-up all users and restore all users, which can also be used to migrate database.
In the case of SQLite, it can also be used to apply some database changes not supported *on the fly* by SQLite (and which cannot be done in a Web session in PHP due to the risk of timeout and damaging the database).

@math-GH Using an old SQLite database, could you try a migration to a refreshed SQLite database?

```sh
./cli/db-backup.php
./cli/db-restore.php --force-overwrite
```

**Comment by math-GH** [comment]
> @math-GH Using an old SQLite database, could you try a migration to a refreshed SQLite database?

How can I identify that it is an old and a new/refreshed database? Or is it enough to export it from my current database and import it into a fresh installation of FreshRSS?

**Comment by Alkarex** [comment]
A test with a copy of the SQLite file with which you observe the `UNIQUE constraint failed` would be perfect

**Comment by math-GH** [comment]
No error and no log entry anymore. But it is a bit strange, because it is possible now to have the same feed URL twice
