### ISSUE TITLE
[BUG] Export feeds crash since 1.20.0

### ISSUE THREAD

**Issue by helmut72** [FreshRSS/FreshRSS#4820]
**Describe the bug**
It's not possible to export feeds in `subscription managment -> import/export -> export`. FreshRSS crashes.

This is the log entry:
```
Uncaught Error: Call to a member function bindParam() on bool in /usr/share/app/app/Models/CategoryDAO.php:228
Stack trace:
#0 /usr/share/app/app/Models/Feed.php(131): FreshRSS_CategoryDAO->searchById()
#1 /usr/share/app/app/Models/Entry.php(670): FreshRSS_Feed->category()
#2 /usr/share/app/app/views/helpers/export/articles.phtml(33): FreshRSS_Entry->toGReader()
#3 /usr/share/app/lib/Minz/View.php(88): include('...')
#4 /usr/share/app/lib/Minz/View.php(138): Minz_View->includeFile()
#5 /usr/share/app/lib/Minz/View.php(149): Minz_View->renderHelper()
#6 /usr/share/app/app/Services/ExportService.php(90): Minz_View->helperToString()
#7 /usr/share/app/app/Controllers/importExportController.php(599): FreshRSS_Export_Service->generateStarredEntries()
#8 /usr/share/app/lib/Minz/Dispatcher.php(119): FreshRSS_importExport_Controller->exportAction()
#9 /usr/share/app/lib/Minz/Dispatcher.php(48): Minz_Dispatcher->launchAction()
#10 /usr/share/app/lib/Minz/FrontController.php(76): Minz_Dispatcher->run()
#11 /usr/share/app/p/i/index.php(57): Minz_FrontController->run()
#12 {main}\n  thrown in /usr/share/app/app/Models/CategoryDAO.php on line 228
```

**To Reproduce**
1. Go to 'subscription managment -> import/export -> export'
2. Click in the box on 'FreshRSS releases'
3. Click on 'export'

**Expected behavior**
No crash like with 1.19.2 and 1.18.1.

**Environment information (please complete the following information):**
- FreshRSS version: 1.20.0
- PHP version: 8.0 (Alpine) or 8.1 (Ubuntu 22)
- Installation type: Docker self hosted

**Comment by aledeg** [comment]
I've tried and it's working properly for me. I am using the latest version on the dev branch. Maybe it was fixed between the release and now.

**Comment by helmut72** [comment]
Did a git clone -depth=1 right now, moved/replaced all files to my app folder: "Your current version of FreshRSS is 1.20.1-dev"
Result: still doesn't work

Unpacked 1.19.1, moved/replaced all files to my app folder: "Your current version of FreshRSS is 1.19.2"
Result: works

Updated again to 1.20.0.
Result: doesn't work

Database is MariaDB Docker image `mariadb:10-focal` (server 10.7.3-MariaDB-1:10.7.3+maria~focal)

Browser Output (not the log) in FreshRSS is just one line:
```
{ "id": "user/myusername/state/org.freshrss/feed/1", "title": "List of FreshRSS releases articles", "author": "myusername", "items": [
```

**Comment by Alkarex** [comment]
The exception should now be avoided with this patch https://github.com/FreshRSS/FreshRSS/pull/4822
However, I could not reproduce the problem.
Could you check whether you have any logs in MariaDB?
Could you try the patch and tell us what output you get after that?

**Comment by helmut72** [comment]
Unfortunately another error:
```
AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function bindParam() on bool in /var/www/html/app/Models/CategoryDAO.php:228\n
Stack trace:\n
#0 /var/www/html/app/Models/Feed.php(131): FreshRSS_CategoryDAO->searchById()\n
#1 /var/www/html/app/Models/Entry.php(670): FreshRSS_Feed->category()\n
#2 /var/www/html/app/views/helpers/export/articles.phtml(33): FreshRSS_Entry->toGReader()\n
#3 /var/www/html/lib/Minz/View.php(88): include('...')\n
#4 /var/www/html/lib/Minz/View.php(138): Minz_View->includeFile()\n
#5 /var/www/html/lib/Minz/View.php(149): Minz_View->renderHelper()\n
#6 /var/www/html/app/Services/ExportService.php(128): Minz_View->helperToString()\n
#7 /var/www/html/app/Controllers/importExportController.php(610): FreshRSS_Export_Service->generateFeedEntries()\n
#8 /var/www/html/lib/Minz/Dispatcher.php(119): FreshRSS_importExport_Controller->exportAction()\n
#9 /var/www/html/lib/Minz/Dispatcher.php(48): Minz_Dispatcher->launchAction()\n
#10 /var/www/html/lib/Minz/FrontController.php(76): Minz_Dispat...'
```

I'm no SQL expert, I hope this is what you ask for:

```
221106 18:17:23	     5 Connect	freshrss@192.168.16.3 on freshrss_db using TCP/IP
		     5 Query	SET NAMES utf8mb4
		     5 Prepare	SELECT c.id AS c_id, c.name AS c_name, c.kind AS c_kind, c.`lastUpdate` AS c_last_update, c.error AS c_error, c.attributes AS c_attributes, f.* FROM `myusername_category` c LEFT OUTER JOIN `myusername_feed` f ON f.category=c.id WHERE f.priority >= ? GROUP BY f.id, c_id ORDER BY c.name, f.name
		     5 Execute	SELECT c.id AS c_id, c.name AS c_name, c.kind AS c_kind, c.`lastUpdate` AS c_last_update, c.error AS c_error, c.attributes AS c_attributes, f.* FROM `myusername_category` c LEFT OUTER JOIN `myusername_feed` f ON f.category=c.id WHERE f.priority >= '0' GROUP BY f.id, c_id ORDER BY c.name, f.name
		     5 Close stmt	
		     5 Prepare	SELECT c.id AS c_id, c.name AS c_name, c.kind AS c_kind, c.`lastUpdate` AS c_last_update, c.error AS c_error, c.attributes AS c_attributes, f.id, f.name, f.url, f.website, f.priority, f.error, f.`cache_nbEntries`, f.`cache_nbUnreads`, f.ttl FROM `myusername_category` c LEFT OUTER JOIN `myusername_feed` f ON f.category=c.id WHERE f.priority >= ? GROUP BY f.id, c_id ORDER BY c.name, f.name
		     5 Execute	SELECT c.id AS c_id, c.name AS c_name, c.kind AS c_kind, c.`lastUpdate` AS c_last_update, c.error AS c_error, c.attributes AS c_attributes, f.id, f.name, f.url, f.website, f.priority, f.error, f.`cache_nbEntries`, f.`cache_nbUnreads`, f.ttl FROM `myusername_category` c LEFT OUTER JOIN `myusername_feed` f ON f.category=c.id WHERE f.priority >= '0' GROUP BY f.id, c_id ORDER BY c.name, f.name
		     5 Close stmt	
		     5 Prepare	SELECT e.id FROM `myusername_entry` e INNER JOIN `myusername_feed` f ON e.id_feed = f.id WHERE e.is_favorite=1 OR EXISTS (SELECT et2.id_tag FROM `myusername_entrytag` et2 WHERE et2.id_entry = e.id)  ORDER BY e.id ASC
		     5 Execute	SELECT e.id FROM `myusername_entry` e INNER JOIN `myusername_feed` f ON e.id_feed = f.id WHERE e.is_favorite=1 OR EXISTS (SELECT et2.id_tag FROM `myusername_entrytag` et2 WHERE et2.id_entry = e.id)  ORDER BY e.id ASC
		     5 Close stmt	
		     5 Prepare	SELECT et.id_entry, et.id_tag, t.name FROM `myusername_tag` t INNER JOIN `myusername_entrytag` et ON et.id_tag = t.id
		     5 Execute	SELECT et.id_entry, et.id_tag, t.name FROM `myusername_tag` t INNER JOIN `myusername_entrytag` et ON et.id_tag = t.id
		     5 Close stmt	
		     5 Prepare	SELECT e0.id, e0.guid, e0.title, e0.author, UNCOMPRESS(content_bin) AS content, e0.link, e0.date, e0.is_read, e0.is_favorite, e0.id_feed, e0.tags, e0.attributes FROM `myusername_entry` e0 INNER JOIN (SELECT e.id FROM `myusername_entry` e INNER JOIN `myusername_feed` f ON e.id_feed = f.id WHERE e.is_favorite=1 OR EXISTS (SELECT et2.id_tag FROM `myusername_entrytag` et2 WHERE et2.id_entry = e.id)  ORDER BY e.id ASC) e2 ON e2.id=e0.id ORDER BY e0.id ASC
		     5 Execute	SELECT e0.id, e0.guid, e0.title, e0.author, UNCOMPRESS(content_bin) AS content, e0.link, e0.date, e0.is_read, e0.is_favorite, e0.id_feed, e0.tags, e0.attributes FROM `myusername_entry` e0 INNER JOIN (SELECT e.id FROM `myusername_entry` e INNER JOIN `myusername_feed` f ON e.id_feed = f.id WHERE e.is_favorite=1 OR EXISTS (SELECT et2.id_tag FROM `myusername_entrytag` et2 WHERE et2.id_entry = e.id)  ORDER BY e.id ASC) e2 ON e2.id=e0.id ORDER BY e0.id ASC
		     5 Close stmt	
		     5 Prepare	SELECT * FROM `myusername_feed` WHERE id=?
		     5 Execute	SELECT * FROM `myusername_feed` WHERE id='1'
		     5 Close stmt	
		     5 Prepare	SELECT c.id AS c_id, c.name AS c_name, c.kind AS c_kind, c.`lastUpdate` AS c_last_update, c.error AS c_error, c.attributes AS c_attributes, f.id, f.name, f.url, f.website, f.priority, f.error, f.`cache_nbEntries`, f.`cache_nbUnreads`, f.ttl FROM `myusername_category` c LEFT OUTER JOIN `myusername_feed` f ON f.category=c.id WHERE f.priority >= ? GROUP BY f.id, c_id ORDER BY c.name, f.name
		     5 Execute	SELECT c.id AS c_id, c.name AS c_name, c.kind AS c_kind, c.`lastUpdate` AS c_last_update, c.error AS c_error, c.attributes AS c_attributes, f.id, f.name, f.url, f.website, f.priority, f.error, f.`cache_nbEntries`, f.`cache_nbUnreads`, f.ttl FROM `myusername_category` c LEFT OUTER JOIN `myusername_feed` f ON f.category=c.id WHERE f.priority >= '0' GROUP BY f.id, c_id ORDER BY c.name, f.name
		     5 Close stmt	
		     5 Prepare	SELECT e.id FROM `myusername_entry` e INNER JOIN `myusername_feed` f ON e.id_feed = f.id WHERE e.id_feed=?  ORDER BY e.id ASC LIMIT 50
		     5 Execute	SELECT e.id FROM `myusername_entry` e INNER JOIN `myusername_feed` f ON e.id_feed = f.id WHERE e.id_feed='1'  ORDER BY e.id ASC LIMIT 50
		     5 Close stmt	
		     5 Prepare	SELECT et.id_entry, et.id_tag, t.name FROM `myusername_tag` t INNER JOIN `myusername_entrytag` et ON et.id_tag = t.id AND et.id_entry IN (?,?,?,?,?,?,?,?,?,?)
		     5 Execute	SELECT et.id_entry, et.id_tag, t.name FROM `myusername_tag` t INNER JOIN `myusername_entrytag` et ON et.id_tag = t.id AND et.id_entry IN ('1667722026029105','1667722026029106','1667722026029107','1667722026029108','1667722026029109','1667722026029110','1667722026029111','1667722026029112','1667722026029113','1667722026029114')
		     5 Close stmt	
		     5 Prepare	SELECT e0.id, e0.guid, e0.title, e0.author, UNCOMPRESS(content_bin) AS content, e0.link, e0.date, e0.is_read, e0.is_favorite, e0.id_feed, e0.tags, e0.attributes FROM `myusername_entry` e0 INNER JOIN (SELECT e.id FROM `myusername_entry` e INNER JOIN `myusername_feed` f ON e.id_feed = f.id WHERE e.id_feed=?  ORDER BY e.id ASC LIMIT 50) e2 ON e2.id=e0.id ORDER BY e0.id ASC
		     5 Execute	SELECT e0.id, e0.guid, e0.title, e0.author, UNCOMPRESS(content_bin) AS content, e0.link, e0.date, e0.is_read, e0.is_favorite, e0.id_feed, e0.tags, e0.attributes FROM `myusername_entry` e0 INNER JOIN (SELECT e.id FROM `myusername_entry` e INNER JOIN `myusername_feed` f ON e.id_feed = f.id WHERE e.id_feed='1'  ORDER BY e.id ASC LIMIT 50) e2 ON e2.id=e0.id ORDER BY e0.id ASC
		     5 Close stmt	
		     5 Quit	
```

Don't wonder about the other path /var/www, this is my container for testing. Everything else looks good, no problems until now.

**Comment by Alkarex** [comment]
@helmut72 It does not look like the patch has been applied before your new test. Could you double-check that your `app/Models/CategoryDAO.php` looks like https://github.com/FreshRSS/FreshRSS/pull/4822/files from inside your Docker container?

**Comment by helmut72** [comment]
Oh, sorry. Now I have directly downloaded the file `CategoryDAO.php` and it works now!

Of course also thank you! Should I close the issue?

**Comment by Alkarex** [comment]
Could you please check your output? Ideally compare with an export using a previous version of FreshRSS

**Comment by helmut72** [comment]
Then I want to test it with my productive system, where I have a lot more articles and need to downgrade first. Can try it in the next 2 days.

**Comment by Alkarex** [comment]
A test of the outputs from your test system would already be good
