### ISSUE TITLE
[BUG]Export/Import always times out after update

### ISSUE THREAD

**Issue by vdbhb59** [FreshRSS/FreshRSS#5982]
**Describe the bug**
The export/Import functionality is always timing out upon update to V1.23.0

**To Reproduce**
1. Go to 'Export/Import feature'
2. Click on 'Export'
3. Timeout happens

**Expected behavior**
Export should start for the OPML, instead of timing out.

**Screenshots**
![image](https://github.com/FreshRSS/FreshRSS/assets/60728004/9552fe9c-75f3-4688-a30b-69321fce24be)

**Environment information (please complete the following information):**
- Device: Laptop / Smartphone
- OS: Windows 11 / Zorin 17 / Android 13
- Browser: [Librewolf 121.0-1 / Mull 121.X]
- FreshRSS version: [1.23.0]
- Database version: [5.7.44 - MySQL Community Server (GPL)]
- PHP version: [PHP 8.1]
- Installation type: [e.g. cPanel Shared Hosting]

**Additional context**
Another BUG is also being raised of feed posts not loading beyond 24 hours time separately.
Extensions currently active are:
'TinyTinyRSS API' => true,
'Invidious Video Feed' => true,
'Black List' => false,
'RSS-Bridge' => true,
'Comics in feed' => false

This same error comes in log here too: SQL error searchById|category|toGReader|include ["HY000",2014,"Cannot execute queries while other unbuffered queries are active. Consider using PDOStatement::fetchAll(). Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute."]

**Comment by Alkarex** [comment]
Would you be able to add a debug line in the code?

Insert the following line between lines 106 and 107 (inside the `if`):

```php
Minz_Log::warning(json_encode(debug_backtrace(), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
```

of `./FreshRSS/app/Models/Feed.php`:

https://github.com/FreshRSS/FreshRSS/blob/e9689645383d37231afa9dbbcd9bd765b804046d/app/Models/Feed.php#L104-L110

Likely the same root problem than https://github.com/FreshRSS/FreshRSS/issues/5981

**Comment by Alkarex** [comment]
After the test above (I am interested in the logs, if possible), would you be able to try the `edge` version? I have made some changes, which might hopefully help https://github.com/FreshRSS/FreshRSS/pull/5986

**Comment by vdbhb59** [comment]
> ```
> Minz_Log::warning(json_encode(debug_backtrace(), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
> ```

I did, and the logs keep on going for 7 pages within a span of 45-50 seconds. The same thing over and over.
`SQL error searchById|category|toGReader|include ["HY000",2014,"Cannot execute queries while other unbuffered queries are active. Consider using PDOStatement::fetchAll(). Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute."]`
Also, request timeout still happening.
```
Request Timeout

This request takes too long to process, it is timed out by the server. If it should not be timed out, please contact administrator of this web site to increase 'Connection Timeout'.
``` 
![image](https://github.com/FreshRSS/FreshRSS/assets/60728004/4881208c-4d4d-495c-a568-4684daccbb75)

**Comment by vdbhb59** [comment]
> After the test above (I am interested in the logs, if possible), would you be able to try the `edge` version? I have made some changes, which might hopefully help #5986

Sure. Just help me how to update to edge, and I am glad to do it. I update via ZIP file, as that is how I had installed and always updated.

**Comment by Alkarex** [comment]
The Web interface does not seem to show the logs fully. Could you please check the file `./FreshRSS/data/users/vdbhb59/log.txt` ?

**Comment by vdbhb59** [comment]
> The Web interface does not seem to show the logs fully. Could you please check the file `./FreshRSS/data/users/vdbhb59/log.txt` ?

Sure. Also, here are the error_logs:

1. API (.../feeds/p/api/error_log)
```
[27-Dec-2023 11:14:05 UTC] PHP Fatal error:  Uncaught Minz_PDOConnectionException: Access to database is denied for `HOSTNAME_DBNAME`: SQLSTATE[HY000] [1040] Too many connections in PATH_TO_MY_DEPLOYMENT/feeds/lib/Minz/ModelPdo.php:131
Stack trace:
#0 PATH_TO_MY_DEPLOYMENT/feeds/app/Models/Factory.php(47): Minz_ModelPdo->__construct('hg-spam@outlook...')
#1 PATH_TO_MY_DEPLOYMENT/feeds/p/api/greader.php(824): FreshRSS_Factory::createEntryDao()
#2 PATH_TO_MY_DEPLOYMENT/feeds/p/api/greader.php(1170): GReaderAPI::editTag(Array, 'user/-/state/co...', '')
#3 PATH_TO_MY_DEPLOYMENT/feeds/p/api/greader.php(1210): GReaderAPI::parse()
#4 {main} thrown in PATH_TO_MY_DEPLOYMENT/feeds/lib/Minz/ModelPdo.php on line 131
[27-Dec-2023 11:14:08 UTC] PHP Fatal error:  Uncaught Minz_PDOConnectionException: Access to database is denied for `HOSTNAME_DBNAME`: SQLSTATE[HY000] [1040] Too many connections in PATH_TO_MY_DEPLOYMENT/feeds/lib/Minz/ModelPdo.php:131
Stack trace:
#0 PATH_TO_MY_DEPLOYMENT/feeds/app/Models/Factory.php(47): Minz_ModelPdo->__construct('Zker67')
#1 PATH_TO_MY_DEPLOYMENT/feeds/p/api/fever.php(163): FreshRSS_Factory::createEntryDao()
#2 PATH_TO_MY_DEPLOYMENT/feeds/p/api/fever.php(179): FeverAPI->authenticate()
#3 PATH_TO_MY_DEPLOYMENT/feeds/p/api/fever.php(572): FeverAPI->isAuthenticatedApiUser()
#4 {main} thrown in PATH_TO_MY_DEPLOYMENT/feeds/lib/Minz/ModelPdo.php on line 131
[27-Dec-2023 11:15:22 UTC] PHP Fatal error:  Uncaught Minz_PDOConnectionException: Access to database is denied for `HOSTNAME_DBNAME`: SQLSTATE[HY000] [1040] Too many connections in PATH_TO_MY_DEPLOYMENT/feeds/lib/Minz/ModelPdo.php:131
Stack trace:
#0 PATH_TO_MY_DEPLOYMENT/feeds/app/Models/Factory.php(47): Minz_ModelPdo->__construct('Zker67')
#1 PATH_TO_MY_DEPLOYMENT/feeds/p/api/fever.php(163): FreshRSS_Factory::createEntryDao()
#2 PATH_TO_MY_DEPLOYMENT/feeds/p/api/fever.php(179): FeverAPI->authenticate()
#3 PATH_TO_MY_DEPLOYMENT/feeds/p/api/fever.php(572): FeverAPI->isAuthenticatedApiUser()
#4 {main} thrown in PATH_TO_MY_DEPLOYMENT/feeds/lib/Minz/ModelPdo.php on line 131
```

2. API (.../feeds/p/i/error_log)
```
PHP Fatal error:  Uncaught TypeError: array_slice(): Argument #3 ($length) must be of type ?int, string given in PATH_TO_MY_DEPLOYMENT/feeds/app/views/index/normal.phtml:89
Stack trace:
#0 PATH_TO_MY_DEPLOYMENT/feeds/app/views/index/normal.phtml(89): array_slice(Array, 0, '7')
#1 PATH_TO_MY_DEPLOYMENT/feeds/lib/Minz/View.php(93): include('/home2/HOSTNAME...')
#2 PATH_TO_MY_DEPLOYMENT/feeds/lib/Minz/View.php(115): Minz_View->includeFile('/views/index/no...')
#3 PATH_TO_MY_DEPLOYMENT/feeds/app/layout/layout.phtml(73): Minz_View->render()
#4 PATH_TO_MY_DEPLOYMENT/feeds/lib/Minz/View.php(93): include('/home2/HOSTNAME...')
#5 PATH_TO_MY_DEPLOYMENT/feeds/lib/Minz/View.php(106): Minz_View->includeFile('/layout/layout....')
#6 PATH_TO_MY_DEPLOYMENT/feeds/lib/Minz/View.php(73): Minz_View->buildLayout()
#7 PATH_TO_MY_DEPLOYMENT/feeds/lib/Minz/Dispatcher.php(59): Minz_View->build()
#8 PATH_TO_MY_DEPLOYMENT/feeds/lib/Minz/FrontController.php(61): Minz_Dispatcher->run()
#9 PATH_TO_MY_DEPLOYMENT/feeds/p/i/index.php(59): Minz_FrontController->run()
```

3. For the /data/user/uname/logs:
It just shows running the different modules/php stuff running & then throwing the same error at the end (the file is too big and contains all my feed URLs and stuff):
```
[Wed, 27 Dec 2023 20:14:17 +0530] [notice] --- Log rotate.
[Wed, 27 Dec 2023 20:14:17 +0530] [error] --- SQL error searchById|category|toGReader|include ["HY000",2014,"Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute."]
```

**Comment by Alkarex** [comment]
Hum, those are not the logs I was hoping for (more details in number 3 would be nice), but one of the errors you are facing `array_slice` has been fixed in https://github.com/FreshRSS/FreshRSS/pull/5978

Let's move on to test the `edge` version. If you install manually by ZIP, you can do the same with
https://github.com/FreshRSS/FreshRSS/archive/edge.zip

**Comment by vdbhb59** [comment]
> Hum, those are not the logs I was hoping for (more details in number 3 would be nice), but one of the errors you are facing `array_slice` has been fixed in #5978
> 
> Let's move on to test the `edge` version. If you install manually by ZIP, you can do the same with https://github.com/FreshRSS/FreshRSS/archive/edge.zip

I can share the whole file, but it is almost 1000+ lines and has all of my feeds details.
Also, the edge now works (1.23.1-dev), but the console logs still show this for whole 39 pages when I ran the export:
`SQL error searchById|category|toGReader|include ["HY000",2014,"Cannot execute queries while other unbuffered queries are active. Consider using PDOStatement::fetchAll(). Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute."]`

![image](https://github.com/FreshRSS/FreshRSS/assets/60728004/746f966c-eaf0-47b3-8e34-2e1d5f81082f)

**Comment by Alkarex** [comment]
Good that there is some progress.
Now that you are running the `edge` version, could you please put back the extra debug line from higher up?
This is the stack trace I am interested in.

**Comment by vdbhb59** [comment]
> ```
> Minz_Log::warning(json_encode(debug_backtrace(), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
> ```

Added now. Just confirm please if I did it correctly?

`	public function category(): ?FreshRSS_Category {
		if ($this->category === null && $this->categoryId > 0) {
		    Minz_Log::warning(json_encode(debug_backtrace(), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
			$catDAO = FreshRSS_Factory::createCategoryDao();
			$this->category = $catDAO->searchById($this->categoryId);
		}`

![image](https://github.com/FreshRSS/FreshRSS/assets/60728004/fae1efde-38c4-4e62-aeea-26f6845f7637)

**Comment by vdbhb59** [comment]
Also, which file and error logs do you need? Export works, but right now running export logged 75 continuous pages of:

![image](https://github.com/FreshRSS/FreshRSS/assets/60728004/3f0f63bc-ad67-47b4-980f-68984ba093b9)

**Comment by Alkarex** [comment]
Yes, the line looks correct.
Please check the log file directly and not through the Web interface.
The line that has my interest is one copy of the one that starts with a bracket `[` and what follows

**Comment by vdbhb59** [comment]
> Yes, the line looks correct. Please check the log file directly and not through the Web interface. The line that has my interest is one copy of the one that starts with a bracket `[` and what follows

```
[Wed, 27 Dec 2023 21:53:54 +0530] [error] --- SQL error searchById|category|toGReader|include ["HY000",2014,"Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute."]
[Wed, 27 Dec 2023 21:53:54 +0530] [warning] --- [
```

The log file is almost 13MB (422847 lines). Attaching it here (I removed sensitive details, hopefully).

**Comment by Alkarex** [comment]
Thanks, that is helpful 👍🏻  I was only asking for one copy of the message :-)

```json
[
	{
		"file": "PATH/feeds/app/Models/Entry.php",
		"line": 833,
		"function": "category",
		"class": "FreshRSS_Feed",
		"object": {},
		"type": "->",
		"args": []
	}, {
		"file": "PATH/feeds/app/views/helpers/export/articles.phtml",
		"line": 30,
		"function": "toGReader",
		"class": "FreshRSS_Entry",
		"object": {},
		"type": "->",
		"args": [
			"freshrss",
			[]
		]
	}, {
		"file": "PATH/feeds/lib/Minz/View.php",
		"line": 93,
		"args": [
			"PATH/feeds/app/views/helpers/export/articles.phtml"
		],
		"function": "include"
	}, {
		"file": "PATH/feeds/lib/Minz/View.php",
		"line": 143,
		"function": "includeFile",
		"class": "Minz_View",
		"object": {
			"callbackBeforeEntries": null,
			"callbackBeforeFeeds": null,
			"callbackBeforePagination": null,
			"categories": {
				"2": {},
				"35": {},
				"4": {},
				"27": {},
				"34": {},
				"14": {},
				"15": {},
				"17": {},
				"7": {},
				"21": {},
				"8": {},
				"19": {},
				"30": {},
				"29": {},
				"25": {},
				"28": {},
				"20": {},
				"31": {},
				"1": {},
				"22": {}
			},
			"entries": {},
			"feed": {},
			"displaySlider": false,
			"query": null,
			"entryIdsTagNames": [],
			"list_title": "???????????",
			"type": "feed/134",
			"rss_title": "",
			"rss_url": "",
			"rss_base": "",
			"internal_rendering": false
		},
		"type": "->",
		"args": [
			"/views/helpers/export/articles.phtml"
		]
	}, {
		"file": "PATH/feeds/lib/Minz/View.php",
		"line": 154,
		"function": "renderHelper",
		"class": "Minz_View",
		"object": {
			"callbackBeforeEntries": null,
			"callbackBeforeFeeds": null,
			"callbackBeforePagination": null,
			"categories": {
				"2": {},
				"35": {},
				"4": {},
				"27": {},
				"34": {},
				"14": {},
				"15": {},
				"17": {},
				"7": {},
				"21": {},
				"8": {},
				"19": {},
				"30": {},
				"29": {},
				"25": {},
				"28": {},
				"20": {},
				"31": {},
				"1": {},
				"22": {}
			},
			"entries": {},
			"feed": {},
			"displaySlider": false,
			"query": null,
			"entryIdsTagNames": [],
			"list_title": "??????????????",
			"type": "feed/134",
			"rss_title": "",
			"rss_url": "",
			"rss_base": "",
			"internal_rendering": false
		},
		"type": "->",
		"args": [
			"export/articles"
		]
	}, {
		"file": "PATH/feeds/app/Services/ExportService.php",
		"line": 117,
		"function": "helperToString",
		"class": "Minz_View",
		"object": {
			"callbackBeforeEntries": null,
			"callbackBeforeFeeds": null,
			"callbackBeforePagination": null,
			"categories": {
				"2": {},
				"35": {},
				"4": {},
				"27": {},
				"34": {},
				"14": {},
				"15": {},
				"17": {},
				"7": {},
				"21": {},
				"8": {},
				"19": {},
				"30": {},
				"29": {},
				"25": {},
				"28": {},
				"20": {},
				"31": {},
				"1": {},
				"22": {}
			},
			"entries": {},
			"feed": {},
			"displaySlider": false,
			"query": null,
			"entryIdsTagNames": [],
			"list_title": "????????????????",
			"type": "feed/134",
			"rss_title": "",
			"rss_url": "",
			"rss_base": "",
			"internal_rendering": false
		},
		"type": "->",
		"args": [
			"export/articles"
		]
	}, {
		"file": "PATH/feeds/app/Controllers/importExportController.php",
		"line": 635,
		"function": "generateFeedEntries",
		"class": "FreshRSS_Export_Service",
		"object": {},
		"type": "->",
		"args": [
			134,
			50
		]
	}, {
		"file": "PATH/feeds/lib/Minz/Dispatcher.php",
		"line": 120,
		"function": "exportAction",
		"class": "FreshRSS_importExport_Controller",
		"object": {},
		"type": "->",
		"args": []
	}, {
		"file": "PATH/feeds/lib/Minz/Dispatcher.php",
		"line": 51,
		"function": "launchAction",
		"class": "Minz_Dispatcher",
		"object": {},
		"type": "->",
		"args": [
			"exportAction"
		]
	}, {
		"file": "PATH/feeds/lib/Minz/FrontController.php",
		"line": 61,
		"function": "run",
		"class": "Minz_Dispatcher",
		"object": {},
		"type": "->",
		"args": []
	}, {
		"file": "PATH/feeds/p/i/index.php",
		"line": 59,
		"function": "run",
		"class": "Minz_FrontController",
		"object": {},
		"type": "->",
		"args": []
	}
]
```

**Comment by Alkarex** [comment]
Would you be able to try this patch? https://github.com/FreshRSS/FreshRSS/pull/5988

**Comment by vdbhb59** [comment]
Sorry for that longgg log file. Removed it now.
Will try the patch tomorrow from my laptop. I will manually change the code file in my path.

**Comment by vdbhb59** [comment]
> Would you be able to try this patch? #5988

Worked. No logs generated and export worked perfectly. Should I keep a watch for 2-3 days to ensure everything works fine, throughout?

**Comment by Alkarex** [comment]
Super, thanks for the tests
