### ISSUE TITLE
[Feature] export custom date format (used in webscraping) to OPML

### ISSUE THREAD

**Issue by geogiraux** [FreshRSS/FreshRSS#6778]
**Is your feature request related to a problem? Please describe.**
My use case is (again) moving from one instance to another, but I can also think of backup : I'd like, like the others fields, to export and import the field used in interpreting the date when scraping XHTML+CSS

**Describe the solution you’d like**
A new field in OPML file called frss:TimestampCustomFormat

**Describe alternatives you’ve considered**
None (I don't admin my own instance)

**Additional context**
I wold be happy to provide more

**Comment by Alkarex** [comment]
Clearly a bug. Fixed in https://github.com/FreshRSS/FreshRSS/pull/6779
Tests welcome

**Comment by Alkarex** [comment]
Merged in our rolling release *edge*

**Comment by geogiraux** [comment]
tested today on an hosted instance (showing FreshRSS version at 1.24.3-dev), still doesn't seem to work : thre is no itemTimeFormat string in the exported OPML

**Comment by Alkarex** [comment]
The server must be newer than https://github.com/FreshRSS/FreshRSS/pull/6779 , so `1.24.3` or `1.25.0-dev`
